[build-system]
requires = ["setuptools"]
build-backend = "setuptools.backends.legacy:build"

[project]
name = "argos"
version = "0.1.0"
dependencies = [
    "smbus2",
    "RPi.GPIO",
    "pyserial",
]
